apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace | default "dev" }}  # Use the default namespace if not specified
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: nginx
  ports:
  - port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.port | default 80 }}
    nodePort: {{ .Values.service.nodePort | default 31701 }}