apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
